'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ActivityPage_Pad2
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''AnsweredMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnsweredMode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ArrNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArrNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''OrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LastQuestionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastQuestionNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdQuestionId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdQuestionId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Hider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hider As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MainDivPad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainDivPad As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivReportExam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivReportExam As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tdReportDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdReportDetail As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHidden As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgHere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHere As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''ExamNumSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExamNumSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spnTotalQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnTotalQuestion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSumScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divSelectExplain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSelectExplain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivNotHaveDontReplyChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivNotHaveDontReplyChoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ShowLimitAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowLimitAmount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mainIntro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainIntro As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMainQuestionAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMainQuestionAnswer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SPmainIntro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPmainIntro As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table4 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''SPIntroDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPIntroDetail As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''SPViewLimitAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPViewLimitAmount As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''mainQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainQuestion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''QuestionTbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionTbl As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''QuestionTd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionTd As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''mainAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainAnswer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''AnswerTbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnswerTbl As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''AnswerExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnswerExp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrev As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''introHtml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents introHtml As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivVs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivVs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''HDIsScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDIsScore As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HDStatusHomework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDStatusHomework As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HDQQ_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDQQ_No As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HDIsLeapChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDIsLeapChoice As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hdNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdNum As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''keepSumseconds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents keepSumseconds As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''CheckIsHaveLeapChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckIsHaveLeapChoice As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''QuantityLeapChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuantityLeapChoice As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hdStatusDict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdStatusDict As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HDNotReplyMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNotReplyMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HDIsSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDIsSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HDLastChoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDLastChoice As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hdUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hdIsGroupEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdIsGroupEng As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
