'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReviewMostWrongAnswer

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ShowBtnOnTapMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowBtnOnTapMenu As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ShowMenuOnPosTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowMenuOnPosTop As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ShowReviewMostWrong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowReviewMostWrong As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sortQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sortQuestion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTestsetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTestsetName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImgRed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgRed As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImgGreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgGreen As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChart As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrvTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrvTop As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblNoExam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoExam As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNextTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextTop As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblSideText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SideRed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideRed As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SideGreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideGreen As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblSideChartWrong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideChartWrong As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSideChartCorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideChartCorrect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrvSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrvSide As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnNextSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextSide As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblNoExamSide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoExamSide As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mainQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainQuestion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''QuestionTbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionTbl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''QuestionTd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionTd As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''mainAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainAnswer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''AnswerTbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnswerTbl As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''AnswerExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnswerExp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BackSlide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackSlide As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''NextSlide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextSlide As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''mainReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainReview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSortQuestionNormal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortQuestionNormal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSortQuestionMostWrong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortQuestionMostWrong As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Help control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Help As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
