'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SettingActivity_PadTeacher

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SetupAnswer_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetupAnswer_Name As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QuestionAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionAmount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTestsetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTestsetName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQuestionAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkUseTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseTemplate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkQuizUseTablet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQuizUseTablet As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkQuizFromSoundlab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQuizFromSoundlab As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRandomQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRandomQuestion As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRandomAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRandomAnswer As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDiffQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDiffQuestion As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCheckTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCheckTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IsPerQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsPerQuestion As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''txtTimePerQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimePerQuestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTimeAllPerQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeAllPerQuestion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IsAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsAll As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''txtTimeAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeAll As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTimeAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkSelfPace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSelfPace As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowAnswer As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rdbAnswerPerQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbAnswerPerQuestion As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''chkRushMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRushMode As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkInShow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkInShow1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTimeShowAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeShowAnswer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdbAnswerAfter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbAnswerAfter As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''chkShowScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowScore As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rdbByStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbByStep As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''rdbEndQuiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbEndQuiz As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''chkUseTools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseTools As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWithCalculator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithCalculator As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWithDictionary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithDictionary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWithWordBook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithWordBook As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWithNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithNotes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWithProtractor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithProtractor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HiddenTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTest As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PClass As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''MClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MClass As Global.System.Web.UI.HtmlControls.HtmlTableCell
End Class
