'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PreviewAllLogPage

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''GridtblExternallApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternallApp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridtblExternalAppStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternalAppStation As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridtblExternalLogAppStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternalLogAppStation As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridtblExternalLogApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternalLogApp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridtblExternalLogAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternalLogAction As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridtblExternalAppQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternalAppQuestion As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridtblExternalAppAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridtblExternalAppAnswer As Global.System.Web.UI.WebControls.GridView
End Class
