'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\sql2008;Initial Catalog=Tablet360;Persist Security Info=True;User I"& _ 
            "D=sa;Password=love")>  _
        Public ReadOnly Property Tablet360ConnectionString() As String
            Get
                Return CType(Me("Tablet360ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.111\sqlserver2008,1501;Initial Catalog=QuickTest_9_fromSuppo"& _ 
            "rt_20130214_noon;Persist Security Info=True;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.111\sqlserver2008,1501;Initial Catalog=QuickTest_9_fromSuppo"& _ 
            "rt_20130214_noon;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString1() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.111\sqlserver2008,1501;Initial Catalog=QuickTest_9_fromSuppo"& _ 
            "rt_20130214_noon;User ID=sa;Password=kl123")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString2() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.116\sqlserver2008,1600;Initial Catalog=QuickTest_9_fromSuppo"& _ 
            "rt_20130214_noon;Persist Security Info=True;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString3() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.116\sqlserver2008,1600;Initial Catalog=QuickTest_9_fromSuppo"& _ 
            "rt_20130214_noon;Persist Security Info=True;User ID=sa;Password=kl123")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString4() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.116\sqlserver2008,1600;Initial Catalog=QuickTest_9_Tester;Us"& _ 
            "er ID=sa")>  _
        Public ReadOnly Property QuickTest_9_TesterConnectionString() As String
            Get
                Return CType(Me("QuickTest_9_TesterConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.116\sqlserver2008,1600;Initial Catalog=QuickTest_9_Tester;Pe"& _ 
            "rsist Security Info=True;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9_TesterConnectionString1() As String
            Get
                Return CType(Me("QuickTest_9_TesterConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.80\sql2008r2;Initial Catalog=QuickTest_9;Persist Security In"& _ 
            "fo=True;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9ConnectionString() As String
            Get
                Return CType(Me("QuickTest_9ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.80\sql2008r2;Initial Catalog=Quicktest_9_Tester;Persist Secu"& _ 
            "rity Info=True;User ID=sa")>  _
        Public ReadOnly Property Quicktest_9_TesterConnectionString2() As String
            Get
                Return CType(Me("Quicktest_9_TesterConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.72;Initial Catalog=QuickTest_9_fromSupport_20130214_noon;Per"& _ 
            "sist Security Info=True;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString5() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.72;Initial Catalog=QuickTest_9_fromSupport_20130214_noon;Per"& _ 
            "sist Security Info=True;User ID=sa;Password=kl123")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString6() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString6"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.90;Initial Catalog=QuickTest_9_fromSupport_20130214_noon;Use"& _ 
            "r ID=sa")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString7() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString7"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.1.90;Initial Catalog=QuickTest_9_fromSupport_20130214_noon;Per"& _ 
            "sist Security Info=True;User ID=sa")>  _
        Public ReadOnly Property QuickTest_9_fromSupport_20130214_noonConnectionString8() As String
            Get
                Return CType(Me("QuickTest_9_fromSupport_20130214_noonConnectionString8"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.BusinessTablet360.My.MySettings
            Get
                Return Global.BusinessTablet360.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
