'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserPage
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''HeaderDetailText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderDetailText As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''IsAllowUpdateSchoolShortName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsAllowUpdateSchoolShortName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkIsContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsContact As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtPreficSchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreficSchool As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdbAllSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbAllSubject As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdbSelectSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbSelectSubject As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''btnOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DetailDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''radioP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioP As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''radioM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioM As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''radioPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioPM As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''PanelUserSubjectClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelUserSubjectClass As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ChkAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkAll As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PrimaryPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrimaryPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''C4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C4_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C4_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C5_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C5_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C6_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C6_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C7_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C7_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C8_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C8_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C9_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C9_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MiddlePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiddlePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''C10_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C10_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C10_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C11_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C11_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C12_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C12_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C13_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C13_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C14_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C14_8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C15_8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C15_8 As Global.System.Web.UI.WebControls.CheckBox
End Class
