'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DashboardStudentPage

    '''<summary>
    '''MyCtlTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyCtlTerm As Global.QuickTest.SelectTermControl

    '''<summary>
    '''MyCtlStudentList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyCtlStudentList As Global.QuickTest.StudentListControl

    '''<summary>
    '''RoomsHaveQuizAndHomework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomsHaveQuizAndHomework As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
