'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HomewokNowAndHistoryPage

    '''<summary>
    '''FormHowworkNowAndHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormHowworkNowAndHistory As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''MyCtlTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyCtlTerm As Global.QuickTest.SelectTermControl

    '''<summary>
    '''BtnCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCurrent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MainDivHomework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainDivHomework As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ModeClassName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModeClassName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdKeepModeRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdKeepModeRoom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''IsSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsSelected As Global.System.Web.UI.WebControls.HiddenField
End Class
