'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StudentListPage

    '''<summary>
    '''hdKeepModeRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdKeepModeRoom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''MyCtlTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyCtlTerm As Global.QuickTest.SelectTermControl

    '''<summary>
    '''lblClassRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClassRoom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowStudentSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowStudentSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ShowStudentSelectedRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowStudentSelectedRoom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ModeClassName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModeClassName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
