Public Class UseTabletDetailDTO

    Public Property RowNumber As Long?
    Public Property School_Code As String
    Public Property Student_Code As String
    Public Property Student_Id As Guid?
    Public Property Student_PrefixName As String
    Public Property Student_Code_Like As String
    Public Property Student_FirstName As String
    Public Property Student_FirstName_Like As String
    Public Property Student_LastName As String
    Public Property Student_LastName_Like As String
    Public Property Teacher_FullName As String
    Public Property Class_Name As String
    Public Property Room_Name As String
    Public Property Class_Room As String
    Public Property Start_Time As Date?
    Public Property End_Time As Date?
    Public Property DiffMin As Integer?
    Public Property Hr As Integer?
    Public Property Mn As Integer?
    Public Property Start_Time_String As String
    Public Property End_Time_String As String
    Public Property Total_Time_String As String
    Public Property Student_Percent_CheckName As String
    Public Property Student_Use_OutClass As String
    Public Property Student_Read_OutClass As String
    Public Property Student_Test_Summary As String
    Public Property Student_Homework_Summary As String
    Public Property Unit_Name As String
    Public Property Lesson_Name As String
    Public Property Part_Name As String
    Public Property Subject_Name As String
    Public Property Use_OutClassName As String
    Public Property Check_Name As Boolean?
    Public Property Condition_Check_Name As Boolean?
    Public Property Condition_UseOutClass As Boolean?
    Public Property Condition_ReadOutClass As Boolean?
    Public Property Condition_Test As Boolean?
    Public Property Condition_Homework As Boolean?
    Public Property Count_AllCheckName As Integer?
    Public Property Count_CheckName As Integer?
    Public Property Percent_CheckName As Decimal?
    Public Property Count_UseOutClass As Integer?
    Public Property SumMin_UseOutClass As Integer?
    Public Property Hr_UseOutClass As Integer?
    Public Property Mn_UseOutClass As Integer?
    Public Property Count_ReadOutClass As Integer?
    Public Property SumMin_ReadOutClass As Integer?
    Public Property Hr_ReadOutClass As Integer?
    Public Property Mn_ReadOutClass As Integer?
    Public Property Sum_ScoreFullTest As Decimal?
    Public Property Sum_ScoreAvailableTest As Decimal?
    Public Property Percent_Test As Decimal?
    Public Property Sum_ScoreFullHomework As Decimal?
    Public Property Sum_ScoreAvailableHomework As Decimal?
    Public Property Percent_Homework As Decimal?

End Class
