'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TeacherStudentDetailPage

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SelectTermControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectTermControl1 As Global.QuickTest.SelectTermControl

    '''<summary>
    '''DivStudentDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivStudentDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSevenDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSevenDay As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFifteenDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFifteenDay As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMonth As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTerm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHomework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHomework As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnQuizHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuizHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPracticeHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPracticeHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DivBottomInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivBottomInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToggle As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
