'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProblemQuestionSummary
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProblem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdited As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnComplete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnProblem As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlLevelProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLevelProblem As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlGroupSubjectProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGroupSubjectProblem As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProblem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProblem As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnEdited As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlLevelEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLevelEdited As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlGroupSubjectEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGroupSubjectEdited As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEdited As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptEdited As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnComplete As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlLevelComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLevelComplete As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlGroupSubjectComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGroupSubjectComplete As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptComplete As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox
End Class
