'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChooseTestsetMaxONet
    
    '''<summary>
    '''LimitAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LimitAmount As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''spnCreditAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnCreditAmount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpireDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''daily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents daily As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
