'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChooseTestset

    '''<summary>
    '''formChooseTestSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formChooseTestSet As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''chkShowCompleteTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompleteTS As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divHomeWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHomeWork As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RptHomeWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RptHomeWork As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divWithoutHomework control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWithoutHomework As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Listing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Listing As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''HdChkSpareTablet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdChkSpareTablet As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
