'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateTabletWithOwner

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''BtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSchoolCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSchoolCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSchoolCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchoolCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSchoolPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSchoolPass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSchoolPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchoolPass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTeacherName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeacherName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTeacherName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeacherName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTeacherLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeacherLastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTeacherLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeacherLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTeacherClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeacherClass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChkTC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkTC12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkTC12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTeacherRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeacherRoom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTeacherSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeacherSubject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChkJubject1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkJubject8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJubject8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveTeacher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveTeacher As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudentName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblStudentLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentLastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStudentLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudentLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblStudentNoInRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentNoInRoom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStudentNoInRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudentNoInRoom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStudentRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudentRoom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblClassStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClassStudent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd6 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd7 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd8 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd9 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd10 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd11 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd12 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblStudentCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudentCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStudentCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudentCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveStudent As Global.System.Web.UI.WebControls.Button
End Class
